# Generated by Django 4.2.1 on 2023-05-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watermanagement',
            name='allot_water',
            field=models.CharField(default='', max_length=10),
        ),
    ]
