# Generated by Django 4.2.1 on 2023-05-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterapp', '0002_watermanagement_allot_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watermanagement',
            name='allot_water',
        ),
        migrations.AddField(
            model_name='watermanagement',
            name='num_guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watermanagement',
            name='total_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='watermanagement',
            name='total_water_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
